definitions:
  models.Moves:
    properties:
      black_win:
        type: integer
      draw:
        type: integer
      new_column:
        type: integer
      new_row:
        type: integer
      next:
        additionalProperties:
          $ref: '#/definitions/models.Moves'
        type: object
      piece:
        type: string
      previous_column:
        type: integer
      previous_row:
        type: integer
      white_win:
        type: integer
    type: object
  models.Outcome:
    additionalProperties:
      additionalProperties:
        type: integer
      type: object
    type: object
info:
  contact: {}
paths:
  /games/outcomes:
    post:
      consumes:
      - application/json
      description: Retrieve outcomes using the moves played
      parameters:
      - description: Moves object
        in: body
        name: moves
        required: true
        schema:
          $ref: '#/definitions/models.Moves'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Outcome'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get outcomes for moves
      tags:
      - games
swagger: "2.0"
